<?php
/**
 * @file
 * Session configuration Drupal module.
 */

///**
// * Implements hook_init().
// *
// * Sets the session lifetime based on the module's setting.
// * Saves the original session cookie lifetime.
// */
//function session_cookie_lifetime_init() {
//  $original_cookie_params = session_get_cookie_params();
//  session_cookie_lifetime_set_original_lifetime($original_cookie_params['lifetime']);
//
//  $cookie_lifetime = session_cookie_lifetime_get_lifetime();
//  if ($cookie_lifetime !== NULL) {
//    session_set_cookie_params($cookie_lifetime);
//  }
//}
//
///**
// * Get the session cookie lifetime.
// *
// * @return int|null
// *   NUll is server default, otherwise it's the expiry time in seconds.
// */
//function session_cookie_lifetime_get_lifetime() {
//  $type = variable_get('session_cookie_lifetime_type', 'default');
//
//  $lifetime = 0;
//
//  switch ($type) {
//    case 'default':
//      $lifetime = NULL;
//      break;
//
//    case 'browser_session':
//      $lifetime = 0;
//      break;
//
//    case 'time':
//      $amount = variable_get('session_cookie_lifetime_amount', 0);
//      $multiplier = variable_get('session_cookie_lifetime_multiplier', 60);
//
//      $lifetime = $amount * $multiplier;
//      break;
//  }
//
//  return $lifetime;
//}
//
///**
// * Sets the original session cookie lifetime.
// *
// * @see session_cookie_lifetime_init()
// *
// * @param int $lifetime
// *   Session cookie lifetime in seconds.
// *
// * @return null|int
// *   Session cookie expiry date in seconds.
// */
//function session_cookie_lifetime_set_original_lifetime($lifetime = NULL) {
//  static $original_lifetime = NULL;
//  if ($lifetime !== NULL) {
//    $original_lifetime = $lifetime;
//  }
//
//  return $original_lifetime;
//}
//
///**
// * Gets the original session cookie lifetime.
// *
// * @return null|int
// *   Session cookie expiry date in seconds.
// */
//function session_cookie_lifetime_get_original_lifetime() {
//  return session_cookie_lifetime_set_original_lifetime();
//}
